version: 0.0
os: linux
files:
  - source: /build/libs/papercpnPro-0.0.1-SNAPSHOT.jar
    destination: /data/springboot/papercpnPro
hooks:
  ApplicationStart:
    - location: scripts/start_jar.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_jar.sh
      timeout: 300
      runas: root